### ISSUE TITLE
OpenGL 2.1 as a prerequisite? 

### ISSUE THREAD

**Issue by djrollins** [gingerBill/Dunjun#10]
Hi Bill,

Just looking through your tutorial and am looking to get started in the near future. However I noticed in the prerequisites that you include OpenGL 2.1 as the version.

Forgive me if I'm incorrect but when I watched the 3rd video (Drawing with OpenGL) I noticed you were using the modern programmable pipeline, from OpenGL 3.0+, rather than the 2.1 fixed pipeline approach (`glBegin()` and `glEnd()` etc).

Just wondering if this is a mistake in the prerequisites or am I miss-understanding the difference between modern OpenGL and the old-school approach?

Cheers,

Dan

**Comment by gingerBill** [comment]
`glBegin` and `glEnd` are fixed pipeline (pre 2.0). This is a very old fashioned approach and it should be never used (except in some debugging exceptions).

In OpenGL 2.0+, shaders were introduced and this allows for a much more modern approach shader pipeline. OpenGL 2.0 has been around since 2004 and 95% of all computers support it.

OpenGL 3.0+ officially implemented a lot of the extensions that we will be using. The extension we are using however, will be available nonetheless even on OpenGL 2.x platforms.

**Comment by djrollins** [comment]
Ah, I see. I for some reason though 3.0 was the introduction of shader pipeline, not 2.0. My mistake!

Thanks for the information.
